import {Inter_Tight } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata = {
  title: "BLOB-Agency - Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <>{children}</>
        <Footer />
      </body>
     
    </html>
  );
}
